### ISSUE TITLE
feature request - display collections

### ISSUE THREAD

**Issue by Jacknq** [adospace/litedbpad#1]
It would be cool as other drivers do  - display tables and so on in treeview in left pane and to be able to fire query over context menu.

**Comment by adospace** [comment]
I've updated the package to handle your request. Now LinqPad shows collections in treeview and context menu shortcuts seem working well. 
Anyway given the design nature of LiteDB as true schema-less database I couldn't specify any field under collections.

**Comment by Jacknq** [comment]
Absolutely cool stuff! Thanks
Couldbe without all prefix,  but this stuff is awesome, great job. 
To make it super perfect its missing only include method, to show complex fields also in grid like data.include.take()..
