### ISSUE TITLE
Database size exceeds  limit of 0B

### ISSUE THREAD

**Issue by michalhainc** [adospace/litedbpad#3]
Hi opened my db

there is ~7K documents in the Telemetry collection, tried FindAll() and got this error (see screenshot)

LinqPad version: 5.26.01

![image](https://user-images.githubusercontent.com/3962233/47635351-f3463300-db54-11e8-9a42-90517de61420.png)

Count method for example... it works.

**Comment by adospace** [comment]
Are you able to open the database in a standard application? it seems like the database is somewhat corrupted

**Comment by michalhainc** [comment]
Yes I am able to open the db in this app https://github.com/falahati/LiteDBViewer and also in my .net app
so I suppose it is okay.

**Comment by adospace** [comment]
OK, I've updated the driver to latest LiteDB version (4.1.4). Please download the new driver and see if it works. 
In case it doesn't please test connection, it should give you an exception stack trace:

![image](https://user-images.githubusercontent.com/10573253/47781109-35aa7400-dcfd-11e8-9391-843babe2cbeb.png)

**Comment by michalhainc** [comment]
Hi, thanks for trying to resolve the issue.
Updated my lpx file with your latest commit, 
I did what you asked for, here is the result: 

No error on test connection. But Telemetry.FindAll() -> the issue still present
![image](https://user-images.githubusercontent.com/3962233/47909716-fe6ccc00-de90-11e8-9eb1-c776b9ed6a4f.png)

FindOne... same issue:
![image](https://user-images.githubusercontent.com/3962233/47910055-ed708a80-de91-11e8-87b7-a9c8d5b6681c.png)

Count works on this collection:
![image](https://user-images.githubusercontent.com/3962233/47910076-f95c4c80-de91-11e8-94ee-b4cb39a07df0.png)

Same file opened in https://github.com/falahati/LiteDBViewer: 
![image](https://user-images.githubusercontent.com/3962233/47909837-54417400-de91-11e8-8021-722d0dab6e5d.png)


One way how I could help to debug is I will have a look in my db if there is some sensitive data and if not I can send the file over to you.

**Comment by michalhainc** [comment]
I played a bit with the litedb shell and when I try find operation without filter I get this exception directly from litedb: 

![image](https://user-images.githubusercontent.com/3962233/47910602-b00cfc80-de93-11e8-960a-135206700526.png)

So maybe your code just doesn't bubble this exception up to the user. 

This makes me feel that something is really wrong with my db and the https://github.com/falahati/LiteDBViewer just selects first N objects from the collection and doesnt hit this error. 

It looks like few people have hit this issue as well, here is some search in LiteDb gitbug issue list: 
https://github.com/mbdavid/litedb/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Unable+to+cast+object+of+type+%27LiteDB.EmptyPage%27

**Comment by michalhainc** [comment]
Just ignore the previous post... I have now another copy of the db file with double amount of records then before. Now the LiteDb Shell behaves fine when doing find all query, but your linq pad driver has still the same problem. I believe the file before was somehow damaged because stupid me copied it while the app writing to it was running. Now I copied with the app stopped.

**Comment by michalhainc** [comment]
So I cloned your repo and I attached VS debugger to the linqpad and its query processes and I got this stack trace for 'Telemetry.FindOne(x=>true)': 

```
LiteDB.LiteException: Database size exceeds limit of 0B.
   at LiteDB.FileDiskService.SetLength(Int64 fileSize)
   at LiteDB.TransactionService.Commit()
   at LiteDB.LiteEngine.Commit()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.EnsureIndex(String collection, String field, Boolean unique)
   at LiteDB.LiteCollection`1.IndexFactory(String field)
   at LiteDB.LiteCollection`1.<Find>b__17_0(String c, String f)
   at LiteDB.Query.Run(CollectionPage col, IndexService indexer)
   at LiteDB.LiteEngine.<Find>d__51.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindOne(Expression`1 predicate)
   at UserQuery.RunUserAuthoredQuery() in C:\Users\mhainc\AppData\Local\Temp\LINQPad5\_vvhyqhid\query_kgyprf.cs:line 37
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
```

**Comment by adospace** [comment]
ok, can you test the new version I've just posted?
Please ensure to use last version (1.0.4) as from your screenshots seems you're using an old one, also ensure that Journal = true and LimitSize = is long.MaxValue (both by default).

![image](https://user-images.githubusercontent.com/10573253/47914265-3ed34680-de9f-11e8-9fdf-76610aad7d8f.png)

![image](https://user-images.githubusercontent.com/10573253/47914275-45fa5480-de9f-11e8-888b-698c67416824.png)

**Comment by michalhainc** [comment]
I already played with these limit numbers, but to no effect, I will try with the new version

**Comment by michalhainc** [comment]
Wonderfull, thank you

![image](https://user-images.githubusercontent.com/3962233/47914711-e8670780-dea0-11e8-8006-dff20fd5841b.png)
