### ISSUE TITLE
Invalid driver file

### ISSUE THREAD

**Issue by bar10dr** [adospace/litedbpad#5]
Hi,

Just downloaded LINQPad 5.36.03.

I get the error message "Invalid driver file" when I try to add the LiteDBPad.lpx file.

**Comment by adospace** [comment]
I've downloaded and installed under LINQPad 5.36.03 and seems working fine. 
Can you rename LiteDBPad.lpx in LiteDBPad.zip and try to decompress it somewhere, just to be sure that file isn't corrupted.

**Comment by bar10dr** [comment]
That was the problem.

Sorry for wasting your time.
