### ISSUE TITLE
Feature request: LINQPad 6 (.lpx6) driver

### ISSUE THREAD

**Issue by dvdgutzmann** [adospace/litedbpad#6]
Hi 

Any chance we'll see a LINQPad 6 driver (.lpx6) any time soon?

I'm just curious, so no pressure ;-) 

Thanks!

David

**Comment by adospace** [comment]
Just got a look at linq pad 6 extensibility documentation and seem pretty easy to port an existing driver over version 6. 
Also I saw that litedb too has moved ahead with a new major version.
I'll try to work on a new version of the driver this we.

**Comment by adospace** [comment]
LinqPad 6 drivers for LiteDB version 4 and 5 are online!
